### ISSUE TITLE
Add Support for DuckDuckGo

### ISSUE THREAD

**Issue by sotdan** [sciancio/websearch#1]
Here is a site detailing some of the advantages of DuckDuckGo: http://donttrack.us/

It also has a lot of great extra features and goodies for nerds.

I'm asking you to consider adding support for this great search engine.

**Comment by sciancio** [comment]
Hi Sodtan,

duckduckgo support is already present. You can right click on the extension icon, click on "Search Options" and select your preferred engine search. Let me know if you have problems.
